tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "autojump"
brew "go"
brew "python@3.8"
brew "typescript", link: false
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "typora"
cask "visual-studio-code"
