code --install-extensions CoenraadS.bracket-pair-colorizer
code --install-extensions Dart-Code.dart-code
code --install-extensions Dart-Code.flutter
code --install-extensions dbaeumer.vscode-eslint
code --install-extensions dsznajder.es7-react-js-snippets
code --install-extensions ecmel.vscode-html-css
code --install-extensions esbenp.prettier-vscode
code --install-extensions formulahendry.code-runner
code --install-extensions Fudge.auto-using
code --install-extensions GitHub.vscode-pull-request-github
code --install-extensions golang.go
code --install-extensions jmrog.vscode-nuget-package-manager
code --install-extensions KevinRose.vsc-python-indent
code --install-extensions kreativ-software.csharpextensions
code --install-extensions mhutchie.git-graph
code --install-extensions ms-azuretools.vscode-docker
code --install-extensions MS-CEINTL.vscode-language-pack-ko
code --install-extensions ms-dotnettools.csharp
code --install-extensions ms-python.python
code --install-extensions ms-python.vscode-pylance
code --install-extensions ms-toolsai.jupyter
code --install-extensions ms-vscode-remote.remote-containers
code --install-extensions ms-vscode.cpptools
code --install-extensions ms-vsliveshare.vsliveshare
code --install-extensions PKief.material-icon-theme
code --install-extensions Shan.code-settings-sync
code --install-extensions xabikos.JavaScriptSnippets
